# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lemma', models.CharField(max_length=100)),
                ('pos', models.CharField(max_length=100)),
                ('freq_ipm', models.FloatField()),
                ('segm_range', models.IntegerField()),
                ('d_coeff', models.IntegerField()),
                ('doc', models.IntegerField()),
            ],
        ),
    ]
