# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstSourceYears',
            fields=[
                ('word_id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('slovoform1', models.CharField(max_length=200)),
                ('number_1700_1710', models.IntegerField(db_column='1700-1710')),
                ('number_1711_1720', models.IntegerField(db_column='1711-1720')),
                ('number_1721_1730', models.IntegerField(db_column='1721-1730')),
                ('number_1731_1740', models.IntegerField(db_column='1731-1740')),
                ('number_1741_1750', models.IntegerField(db_column='1741-1750')),
                ('number_1751_1760', models.IntegerField(db_column='1751-1760')),
                ('number_1761_1770', models.IntegerField(db_column='1761-1770')),
                ('number_1771_1780', models.IntegerField(db_column='1771-1780')),
                ('number_1781_1790', models.IntegerField(db_column='1781-1790')),
                ('number_1791_1800', models.IntegerField(db_column='1791-1800')),
                ('number_1801_1810', models.IntegerField(db_column='1801-1810')),
                ('number_1811_1820', models.IntegerField(db_column='1811-1820')),
                ('number_1821_1830', models.IntegerField(db_column='1821-1830')),
                ('number_1831_1840', models.IntegerField(db_column='1831-1840')),
                ('number_1841_1850', models.IntegerField(db_column='1841-1850')),
                ('number_1851_1860', models.IntegerField(db_column='1851-1860')),
                ('number_1861_1870', models.IntegerField(db_column='1861-1870')),
                ('number_1871_1880', models.IntegerField(db_column='1871-1880')),
                ('number_1881_1890', models.IntegerField(db_column='1881-1890')),
                ('number_1891_1900', models.IntegerField(db_column='1891-1900')),
                ('number_1901_1910', models.IntegerField(db_column='1901-1910')),
                ('number_1911_1920', models.IntegerField(db_column='1911-1920')),
                ('number_1921_1930', models.IntegerField(db_column='1921-1930')),
                ('number_1931_1940', models.IntegerField(db_column='1931-1940')),
                ('number_1941_1950', models.IntegerField(db_column='1941-1950')),
                ('number_1951_1960', models.IntegerField(db_column='1951-1960')),
                ('number_1961_1970', models.IntegerField(db_column='1961-1970')),
                ('number_1971_1980', models.IntegerField(db_column='1971-1980')),
                ('number_1981_1990', models.IntegerField(db_column='1981-1990')),
                ('number_1991_2000', models.IntegerField(db_column='1991-2000')),
                ('number_2001_2010', models.IntegerField(db_column='2001-2010')),
            ],
            options={
                'db_table': 'first_source_years',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SecondSourceYears',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_id', models.IntegerField(db_column='ID')),
                ('slovoform2', models.CharField(max_length=200)),
                ('lemma', models.CharField(max_length=200)),
                ('partofsp', models.CharField(db_column='partOfSp', max_length=50)),
                ('grammar', models.CharField(max_length=200)),
                ('omonim', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'second_source_years',
                'managed': False,
            },
        ),
    ]
