# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_dict', '0003_auto_20170417_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='ByGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lemma', models.CharField(max_length=100)),
                ('pos', models.CharField(max_length=100)),
                ('freq_spoken', models.FloatField()),
                ('freq_news', models.FloatField()),
                ('freq_fiction', models.FloatField()),
                ('freq_nonfiction', models.FloatField()),
            ],
        ),
    ]
